# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI

on:
  push:
    paths:
      - 'scripts/**/*'
      - '.forgejo/workflows/**/*'

env:
  UBIRD_CI: 1
  UBIRD_CHECKOUT_ACTION_COMMIT: "f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a" # v7.0.1
  UBIRD_FEDORA_VERSION: "44"

jobs:
  lint:
    name: Lint
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.UBIRD_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@${{ env.UBIRD_CHECKOUT_ACTION_COMMIT }}

      - name: Lint
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y bash curl shasum tar
          /bin/bash scripts/get_sources.sh shellcheck
          /bin/bash scripts/get_sources.sh shfmt
          /bin/bash scripts/lint.sh
