# uBird common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly UBIRD_ENV_OVERRIDE="${UBIRD_ROOT}/env_override.sh"
if [[ -f "${UBIRD_ENV_OVERRIDE}" ]]; then
    source "${UBIRD_ENV_OVERRIDE}"
fi

# uBird

# Scripts directory
readonly UBIRD_SCRIPTS="${UBIRD_ROOT}/scripts"
export UBIRD_SCRIPTS

## uBird utilities
readonly UBIRD_UTILS="${UBIRD_SCRIPTS}/utilities.sh"
export UBIRD_UTILS

# Build directory
readonly UBIRD_BUILD="${UBIRD_ROOT}/build"
export UBIRD_BUILD

# External sources directory
readonly UBIRD_EXTERNAL="${UBIRD_ROOT}/external"
export UBIRD_EXTERNAL

# External downloads/resources directory
readonly UBIRD_DOWNLOADS="${UBIRD_EXTERNAL}/downloads"
export UBIRD_DOWNLOADS

# Patches directory
readonly UBIRD_PATCHES="${UBIRD_ROOT}/patches"
export UBIRD_PATCHES

# Set our platform and OS
readonly UBIRD_ENV_HELPERS="${UBIRD_SCRIPTS}/env_helpers.sh"
export UBIRD_ENV_HELPERS
source "${UBIRD_ENV_HELPERS}"

# Version info
readonly UBIRD_VERSIONS="${UBIRD_SCRIPTS}/versions.sh"
export UBIRD_VERSIONS

# Outputs directory
readonly UBIRD_OUTPUTS_DEFAULT="${UBIRD_ROOT}/outputs"
if [[ -z "${UBIRD_OUTPUTS+x}" ]]; then
    UBIRD_OUTPUTS="${UBIRD_OUTPUTS_DEFAULT}"
fi
readonly UBIRD_OUTPUTS
export UBIRD_OUTPUTS

# Whether we're targeting ATN or self-distribution
## (The only difference ATM is that ATN builds do not specify an update URL)
readonly UBIRD_ATN_DEFAULT=0
if [[ -z "${UBIRD_ATN+x}" ]]; then
    UBIRD_ATN="${UBIRD_ATN_DEFAULT}"
fi
readonly UBIRD_ATN
export UBIRD_ATN

# uBird add-on ID
readonly UBIRD_ADDON_ID_DEFAULT='ubird-direct@celenity.dev'
if [[ -z "${UBIRD_ADDON_ID+x}" ]]; then
    UBIRD_ADDON_ID="${UBIRD_ADDON_ID_DEFAULT}"
fi
readonly UBIRD_ADDON_ID
export UBIRD_ADDON_ID

# uBird (ATN) add-on ID
readonly UBIRD_ATN_ADDON_ID_DEFAULT='uBird@celenity.dev'
if [[ -z "${UBIRD_ATN_ADDON_ID+x}" ]]; then
    UBIRD_ATN_ADDON_ID="${UBIRD_ATN_ADDON_ID_DEFAULT}"
fi
readonly UBIRD_ATN_ADDON_ID
export UBIRD_ATN_ADDON_ID

# uBird update URL
readonly UBIRD_UPDATE_URL_DEFAULT='https:/releases.celenity.dev/addons/updates.json'
if [[ -z "${UBIRD_UPDATE_URL+x}" ]]; then
    # By default, use our update URL
    UBIRD_UPDATE_URL="${UBIRD_UPDATE_URL_DEFAULT}"
fi
readonly UBIRD_UPDATE_URL
export UBIRD_UPDATE_URL

# Should we create a log file for build.sh? (Default)
readonly UBIRD_LOG_BUILD_DEFAULT=1
if [[ -z "${UBIRD_LOG_BUILD+x}" ]]; then
    UBIRD_LOG_BUILD="${UBIRD_LOG_BUILD_DEFAULT}"
fi
readonly UBIRD_LOG_BUILD
export UBIRD_LOG_BUILD

# Should we create a log file for get_sources.sh? (Default)
readonly UBIRD_LOG_SOURCES_DEFAULT=1
if [[ -z "${UBIRD_LOG_SOURCES+x}" ]]; then
    UBIRD_LOG_SOURCES="${UBIRD_LOG_SOURCES_DEFAULT}"
fi
readonly UBIRD_LOG_SOURCES
export UBIRD_LOG_SOURCES

# Directory where we should store log files (if logging is desired)
readonly UBIRD_LOG_DIR_DEFAULT="${UBIRD_BUILD}/logs"
if [[ -z "${UBIRD_LOG_DIR+x}" ]]; then
    UBIRD_LOG_DIR="${UBIRD_LOG_DIR_DEFAULT}"
fi
readonly UBIRD_LOG_DIR
export UBIRD_LOG_DIR

# GNU awk
if [[ "${UBIRD_OS}" == 'osx' ]]; then
    readonly UBIRD_AWK_DEFAULT='gawk'
else
    readonly UBIRD_AWK_DEFAULT='awk'
fi
if [[ -z "${UBIRD_AWK+x}" ]]; then
    UBIRD_AWK="${UBIRD_AWK_DEFAULT}"
fi
readonly UBIRD_AWK
export UBIRD_AWK

# GNU sed
if [[ "${UBIRD_OS}" == 'osx' ]]; then
    readonly UBIRD_SED_DEFAULT='gsed'
else
    readonly UBIRD_SED_DEFAULT='sed'
fi
if [[ -z "${UBIRD_SED+x}" ]]; then
    UBIRD_SED="${UBIRD_SED_DEFAULT}"
fi
readonly UBIRD_SED
export UBIRD_SED

# GNU tar
if [[ "${UBIRD_OS}" == 'osx' ]]; then
    readonly UBIRD_TAR_DEFAULT='gtar'
else
    readonly UBIRD_TAR_DEFAULT='tar'
fi
if [[ -z "${UBIRD_TAR+x}" ]]; then
    UBIRD_TAR="${UBIRD_TAR_DEFAULT}"
fi
readonly UBIRD_TAR
export UBIRD_TAR

## uAssets (main)
readonly UBIRD_UASSETS_MAIN_DEFAULT="${UBIRD_EXTERNAL}/uassets-main"
if [[ -z "${UBIRD_UASSETS_MAIN+x}" ]]; then
    UBIRD_UASSETS_MAIN="${UBIRD_UASSETS_MAIN_DEFAULT}"
fi
readonly UBIRD_UASSETS_MAIN
export UBIRD_UASSETS_MAIN

## uAssets (prod)
readonly UBIRD_UASSETS_PROD_DEFAULT="${UBIRD_EXTERNAL}/uassets-prod"
if [[ -z "${UBIRD_UASSETS_PROD+x}" ]]; then
    UBIRD_UASSETS_PROD="${UBIRD_UASSETS_PROD_DEFAULT}"
fi
readonly UBIRD_UASSETS_PROD
export UBIRD_UASSETS_PROD

# uBlock Origin
readonly UBIRD_UBO_DEFAULT="${UBIRD_EXTERNAL}/ublock"
if [[ -z "${UBIRD_UBO+x}" ]]; then
    UBIRD_UBO="${UBIRD_UBO_DEFAULT}"
fi
readonly UBIRD_UBO
export UBIRD_UBO

# Cipher suites
## (This enforces strong cipher suites - see ex. https://browserleaks.com/tls)
readonly UBIRD_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${UBIRD_CIPHERS+x}" ]]; then
    UBIRD_CIPHERS="${UBIRD_CIPHERS_DEFAULT}"
fi
readonly UBIRD_CIPHERS
export UBIRD_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly UBIRD_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${UBIRD_CURL_FLAGS_OVERRIDE+x}" ]]; then
    UBIRD_CURL_FLAGS_OVERRIDE="${UBIRD_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly UBIRD_CURL_FLAGS_OVERRIDE
export UBIRD_CURL_FLAGS_OVERRIDE

# curl flags
readonly UBIRD_CURL_FLAGS_DEFAULT="-q --disable --no-netrc -j -e "" -A "" -S --ciphers ${UBIRD_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --tlsv1.2 --trace-time --user-agent "" --verbose"
if [[ -z "${UBIRD_CURL_FLAGS+x}" ]]; then
    readonly UBIRD_CURL_FLAGS="${UBIRD_CURL_FLAGS_DEFAULT}"
elif [[ "${UBIRD_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
    readonly UBIRD_CURL_FLAGS="${UBIRD_CURL_FLAGS}"
else
    readonly UBIRD_CURL_FLAGS="${UBIRD_CURL_FLAGS_DEFAULT} ${UBIRD_CURL_FLAGS}"
fi
export UBIRD_CURL_FLAGS


# We've now set our environment variables...
readonly UBIRD_SET_ENVS=1
export UBIRD_SET_ENVS
