# uBird common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
UBIRD_ENV_OVERRIDE="${UBIRD_ROOT}/env_override.sh"
if [[ -f "${UBIRD_ENV_OVERRIDE}" ]]; then
    source "${UBIRD_ENV_OVERRIDE}"
fi

# uBird

# Scripts directory
export UBIRD_SCRIPTS="${UBIRD_ROOT}/scripts"

# Build directory
export UBIRD_BUILD="${UBIRD_ROOT}/build"

# External sources directory
export UBIRD_EXTERNAL="${UBIRD_ROOT}/external"

# Patches directory
export UBIRD_PATCHES="${UBIRD_ROOT}/patches"

# Set our platform and OS
export UBIRD_ENV_HELPERS="${UBIRD_SCRIPTS}/env_helpers.sh"
source "${UBIRD_ENV_HELPERS}"

# Version info
export UBIRD_VERSIONS="${UBIRD_SCRIPTS}/versions.sh"

# uBird outputs directory
UBIRD_OUTPUTS_DEFAULT="${UBIRD_ROOT}/outputs"
if [[ -z "${UBIRD_OUTPUTS+x}" ]]; then
    export UBIRD_OUTPUTS="${UBIRD_OUTPUTS_DEFAULT}"
fi

# Whether we're targeting ATN or self-distribution
## (The only difference ATM is that ATN builds do not specify an update URL)
UBIRD_ATN_DEFAULT=0
if [[ -z "${UBIRD_ATN+x}" ]]; then
    export UBIRD_ATN="${UBIRD_ATN_DEFAULT}"
fi

# Should we create a log file for build.sh? (Default)
UBIRD_LOG_BUILD_DEFAULT=1
if [[ -z "${UBIRD_LOG_BUILD+x}" ]]; then
    export UBIRD_LOG_BUILD="${UBIRD_LOG_BUILD_DEFAULT}"
fi

# Should we create a log file for get_sources.sh? (Default)
UBIRD_LOG_SOURCES_DEFAULT=1
if [[ -z "${UBIRD_LOG_SOURCES+x}" ]]; then
    export UBIRD_LOG_SOURCES="${UBIRD_LOG_SOURCES_DEFAULT}"
fi

# Directory where we should store log files (if logging is desired)
UBIRD_LOG_DIR_DEFAULT="${UBIRD_BUILD}/logs"
if [[ -z "${UBIRD_LOG_DIR+x}" ]]; then
    export UBIRD_LOG_DIR="${UBIRD_LOG_DIR_DEFAULT}"
fi

# GNU awk
if [[ "${UBIRD_OS}" == 'osx' ]]; then
    UBIRD_AWK_DEFAULT='gawk'
else
    UBIRD_AWK_DEFAULT='awk'
fi
if [[ -z "${UBIRD_AWK+x}" ]]; then
    export UBIRD_AWK="${UBIRD_AWK_DEFAULT}"
fi

# GNU sed
if [[ "${UBIRD_OS}" == 'osx' ]]; then
    UBIRD_SED_DEFAULT='gsed'
else
    UBIRD_SED_DEFAULT='sed'
fi
if [[ -z "${UBIRD_SED+x}" ]]; then
    export UBIRD_SED="${UBIRD_SED_DEFAULT}"
fi

# uBlock Origin
UBIRD_UBO_DEFAULT="${UBIRD_EXTERNAL}/uBlock"
if [[ -z "${UBIRD_UBO+x}" ]]; then
    export UBIRD_UBO="${UBIRD_UBO_DEFAULT}"
fi

# uBird add-on ID
UBIRD_ADDON_ID_DEFAULT='uBird@celenity.dev'
if [[ -z "${UBIRD_ADDON_ID+x}" ]]; then
    # By default, use "uBird@celenity.dev" for the add-on ID
    export UBIRD_ADDON_ID="${UBIRD_ADDON_ID_DEFAULT}"
fi

# uBird update URL
UBIRD_UPDATE_URL_DEFAULT='https://gitlab.com/celenityy/uBird/-/raw/main/updates.json'
if [[ -z "${UBIRD_UPDATE_URL+x}" ]]; then
    # By default, use our GitLab update URL
    export UBIRD_UPDATE_URL="${UBIRD_UPDATE_URL_DEFAULT}"
fi
